[build]
  publish = "dist/2-invoice-app"  # Directorio relativo de publicación
  command = "npm run build"       # Comando de construcción

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

