[build]
  publish = "dist/2-invoice-app"  # Directorio correcto de publicación
  command = "npm run build"  # Comando para construir tu aplicación

[build.environment]
  NODE_VERSION = "18"  # Especifica la versión de Node.js

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
